name: 'Mule Build Action'
description: 'Central script to build mule projects'
author: 'Faisal Khanani'

inputs:
  release-tag:
    description: 'release number to be build'
    required: true
  github-token:
    description: 'GitHub token'
    required: true
  mulesoft-nexus-user:
    description: 'Enterprise repo user'
    required: false
  mulesoft-nexus-password:
    description: 'Enterprise repo password'
    required: false
  test-args:
    description: 'Json object'
    required: false
    default: "{}"    

runs:
  using: 'node12'
  main: 'dist/index.js'
