name: 'Mule Build Action'
description: 'Central script to build mule projects'
author: 'Faisal Khanani'

inputs:
  github-token:
    description: 'GitHub token'
    required: true
  release-tag:
    description: 'release number to be build'
    required: true
  test-args:
    description: 'Json object'
    required: false
    default: "{}"    
env:
  mulesoft_nexus_user:
    required: false  

runs:
  using: 'node12'
  main: 'dist/index.js'
