name: 'Mule Build Action'
description: 'Central script to build mule projects'
author: 'Faisal Khanani'

inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'
